Repository WildCodeSchool/js-orleans-p2-secretbar, pull requests merged in 2020-10, with the labels that each got.

#1 Add styleguide
  src/App.css
  src/App.jsx
Labels: Reviewed

#22 Add folder and files for services section
  package.json
  src/App.jsx
  src/components/section-title/SectionTitle.css
  src/components/section-title/SectionTitle.jsx
  src/components/services/Service.css
  src/components/services/Service.jsx
  src/components/services/ServiceList.css
  src/components/services/ServiceList.jsx
Labels: Reviewed

#24 Fix responsive declaration on App.css
  src/App.css
Labels: Reviewed

#25 add folder and files for events
  src/App.jsx
  src/components/event/Formevent.css
  src/components/event/Formevent.jsx
  src/components/event/Popevent.css
  src/components/event/Popevent.jsx
  src/index.jsx
Labels: Conflicts

#26 Pull Request Dev To Master
  package.json
  src/App.css
  src/App.jsx
  src/components/event/Formevent.css
  src/components/event/Formevent.jsx
  src/components/event/Popevent.css
  src/components/event/Popevent.jsx
  src/components/section-title/SectionTitle.css
  src/components/section-title/SectionTitle.jsx
  src/components/services/Service.css
  src/components/services/Service.jsx
  src/components/services/ServiceList.css
  src/components/services/ServiceList.jsx
  src/index.jsx
Labels: Reviewed

#23 style de la navbar établie
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/components/Navbar.css
  src/components/Navbar.jsx
  src/components/image/accueil.png
  src/components/image/logo.svg
  src/components/image/logoCarte.png
  src/components/image/logobar.png
  src/components/image/portefolio.png
  src/index.jsx
Labels: Changes requested
